# Generated by Django 4.2.2 on 2024-06-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('twitter_id', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('telegram_id', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_followers', models.IntegerField(default=0)),
                ('telegram_subscribers', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'client',
            },
        ),
    ]
