# Generated by Django 4.2.2 on 2024-06-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.IntegerField()),
            ],
            options={
                'db_table': 'crypto',
            },
        ),
    ]
