# Generated by Django 4.2.2 on 2024-06-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinmarketcap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinHistorical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.CharField(max_length=255)),
                ('balance', models.CharField(max_length=255)),
                ('twitter_followers', models.IntegerField(default=0)),
                ('tg_subscribers', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'coin_historical',
            },
        ),
        migrations.CreateModel(
            name='CoinProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.CharField(max_length=255)),
                ('balance', models.CharField(max_length=255)),
                ('twitter_followers', models.IntegerField(default=0)),
                ('tg_subscribers', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'coin_profile',
            },
        ),
        migrations.AlterField(
            model_name='crypto',
            name='coin_id',
            field=models.CharField(max_length=255),
        ),
    ]
